# Generated by Django 6.0.5 on 2026-05-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_function', models.DateField()),
                ('prime_minister', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'government',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('founding', models.IntegerField()),
                ('leader', models.CharField(max_length=75)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'politician',
            },
        ),
        migrations.CreateModel(
            name='GovernmentParty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('government', models.ForeignKey(db_column='id_government', on_delete=django.db.models.deletion.CASCADE, to='politicians.government')),
                ('party', models.ForeignKey(db_column='id_party', on_delete=django.db.models.deletion.CASCADE, to='politicians.party')),
            ],
            options={
                'db_table': 'government_party',
                'unique_together': {('party', 'government')},
            },
        ),
        migrations.CreateModel(
            name='GovernmentOfficial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, choices=[('Minister', 'Minister'), ('Speaker of the house', 'Speaker of the house'), ('Deputy', 'Deputy'), ('Deputy speaker', 'Deputy speaker'), ('Prime minister', 'Prime minister')], max_length=50, null=True)),
                ('start_of_term', models.DateField()),
                ('end_of_term', models.DateField(blank=True, null=True)),
                ('government', models.ForeignKey(db_column='id_government', on_delete=django.db.models.deletion.CASCADE, to='politicians.government')),
                ('office', models.ForeignKey(db_column='id_office', on_delete=django.db.models.deletion.CASCADE, to='politicians.office')),
                ('party', models.ForeignKey(blank=True, db_column='id_party', null=True, on_delete=django.db.models.deletion.SET_NULL, to='politicians.party')),
                ('politician', models.ForeignKey(db_column='id_politician', on_delete=django.db.models.deletion.CASCADE, to='politicians.politician')),
            ],
            options={
                'db_table': 'government_official',
                'unique_together': {('politician', 'government', 'office')},
            },
        ),
        migrations.CreateModel(
            name='PoliticsParty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_of_membership', models.DateField()),
                ('end_of_membership', models.DateField(blank=True, null=True)),
                ('party', models.ForeignKey(db_column='id_party', on_delete=django.db.models.deletion.CASCADE, to='politicians.party')),
                ('politician', models.ForeignKey(db_column='id_politician', on_delete=django.db.models.deletion.CASCADE, to='politicians.politician')),
            ],
            options={
                'db_table': 'politics_party',
                'unique_together': {('politician', 'party')},
            },
        ),
    ]
