# Generated by Django 6.0.5 on 2026-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/parties/'),
        ),
        migrations.AddField(
            model_name='politician',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/politicians/'),
        ),
    ]
