# Generated by Django 6.0.5 on 2026-05-14 06:54

import django.core.validators
import politicians.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_party_photo_file_politician_photo_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='government',
            options={'verbose_name': 'vláda'},
        ),
        migrations.AlterModelOptions(
            name='governmentofficial',
            options={'verbose_name': 'vládní funkce'},
        ),
        migrations.AlterModelOptions(
            name='governmentparty',
            options={'verbose_name': 'vládnoucí strana'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'funkce'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'strana', 'verbose_name_plural': 'strany'},
        ),
        migrations.AlterModelOptions(
            name='politician',
            options={'verbose_name': 'politik', 'verbose_name_plural': 'politici'},
        ),
        migrations.AlterModelOptions(
            name='politicsparty',
            options={'verbose_name': 'strana politika'},
        ),
        migrations.AlterField(
            model_name='government',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='government',
            name='prime_minister',
            field=models.CharField(max_length=50, validators=[politicians.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='governmentofficial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='governmentparty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=200, validators=[politicians.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='party',
            name='founding',
            field=models.IntegerField(validators=[politicians.models.validate_founding_year]),
        ),
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='politician',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='This field must start with a capital letter and contain only letters.', regex='^[A-ZÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ][a-záčďéěíňóřšťúůýž]*$')]),
        ),
        migrations.AlterField(
            model_name='politician',
            name='surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='This field must start with a capital letter and contain only letters.', regex='^[A-ZÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ][a-záčďéěíňóřšťúůýž]*$')]),
        ),
        migrations.AlterField(
            model_name='politicsparty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
